"""Render a brief to Markdown (for export) and provide a clean JSON view.

The web front end consumes the brief JSON directly; this module produces the
downloadable Markdown and is also handy for the CLI and the scoring test.
"""
from __future__ import annotations


def _source_links(source_ids: list[str], index: dict) -> str:
    links = []
    for sid in source_ids or []:
        meta = index.get(sid)
        if meta and meta.get("url"):
            links.append(f"[{meta['label']}]({meta['url']})")
        else:
            links.append(sid)
    return " · ".join(links) if links else ""


def brief_to_markdown(brief: dict) -> str:
    entity = brief.get("entity", {})
    a = brief.get("analysis", {})
    index = brief.get("sourceIndex", {})

    lines: list[str] = []
    lines.append(f"# Verdikt — Strategy Brief: {entity.get('name', brief.get('query'))}")
    lines.append("")
    lines.append(
        f"**{entity.get('kind', '').title()}** · `{entity.get('id', '')}` · "
        f"generated {brief.get('generatedAt', '')} · engine: `{brief.get('engine', '')}`"
    )
    lines.append("")

    # Verdict + confidence
    lines.append(f"## Verdict: {a.get('verdict', '—')}  ·  Confidence {a.get('confidence', '—')}/100")
    lines.append("")
    lines.append(f"> **Recommendation.** {a.get('recommendation', '')}")
    lines.append("")
    if a.get("confidenceRationale"):
        lines.append(f"*Why this score:* {a['confidenceRationale']}")
        lines.append("")
    if a.get("summary"):
        lines.append(a["summary"])
        lines.append("")
    if a.get("longevityAngle"):
        lines.append(f"**Aging & longevity angle.** {a['longevityAngle']}")
        lines.append("")

    if brief.get("analystNote"):
        lines.append(f"> **Your call (human decision).** {brief['analystNote']}")
        lines.append("")

    # (01) Evidence — what each database contributed.
    evidence_log = (brief.get("evidence", {}) or {}).get("evidenceLog", [])
    if evidence_log:
        lines.append("## ① Evidence — what we found")
        lines.append("")
        for e in evidence_log:
            lines.append(f"- **{e.get('label', e.get('source'))}** — {e.get('finding', '')}")
        lines.append("")

    # (02) Reasoning — how we weighed it, step by step.
    steps = a.get("reasoningSteps", [])
    if steps:
        lines.append("## ② Reasoning — how we weighed it")
        lines.append("")
        for i, s in enumerate(steps, 1):
            src = _source_links(s.get("sources", []), index)
            tail = f"  <sub>{src}</sub>" if src else ""
            lines.append(f"{i}. {s.get('step', '')}{tail}")
        lines.append("")

    # Opportunity ranking — strongest age-related indications.
    ranking = a.get("opportunityRanking", [])
    if ranking:
        lines.append("## Opportunity ranking — strongest age-related indications")
        lines.append("")
        for i, o in enumerate(ranking, 1):
            src = _source_links(o.get("sources", []), index)
            tail = f"  <sub>Sources: {src}</sub>" if src else ""
            lines.append(f"{i}. **{o.get('indication', '')}** — {o.get('rationale', '')}{tail}")
        lines.append("")

    def section(title: str, items: list[dict], render):
        lines.append(f"## {title}")
        lines.append("")
        if not items:
            lines.append("_None identified._")
            lines.append("")
            return
        for it in items:
            lines.append(render(it))
        lines.append("")

    section(
        "✅ Supporting evidence",
        a.get("supporting", []),
        lambda it: f"- **{it.get('claim', '')}** — {it.get('detail', '')}  "
        + (f"\n  <sub>Sources: {_source_links(it.get('sources', []), index)}</sub>"
           if it.get("sources") else ""),
    )
    section(
        "⚠️ Contradicting / cautionary evidence",
        a.get("contradicting", []),
        lambda it: f"- **{it.get('claim', '')}** — {it.get('detail', '')}  "
        + (f"\n  <sub>Sources: {_source_links(it.get('sources', []), index)}</sub>"
           if it.get("sources") else ""),
    )
    section(
        "❓ Missing evidence",
        a.get("missing", []),
        lambda it: f"- **{it.get('gap', '')}** — {it.get('whyItMatters', '')}",
    )

    # Source appendix
    lines.append("## Sources")
    lines.append("")
    for sid, meta in index.items():
        lines.append(f"- **{meta.get('label', sid)}** — {meta.get('url', '')}")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Verdikt, the Evidence-to-Decision Engine. "
                 "For research triage only — not medical advice.*")
    return "\n".join(lines)
